//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace iFrameProjectExample.it.sella.testecomm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSCryptDecryptSoap", Namespace="https://ecomm.sella.it/")]
    public partial class WSCryptDecrypt : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EncryptOperationCompleted;
        
        private System.Threading.SendOrPostCallback DecryptOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSCryptDecrypt() {
            this.Url = global::iFrameProjectExample.Properties.Settings.Default.iFrameProjectExample_it_sella_testecomm_WSCryptDecrypt;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EncryptCompletedEventHandler EncryptCompleted;
        
        /// <remarks/>
        public event DecryptCompletedEventHandler DecryptCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ecomm.sella.it/Encrypt", RequestNamespace="https://ecomm.sella.it/", ResponseNamespace="https://ecomm.sella.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode Encrypt(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string shopLogin, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uicCode, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string amount, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string shopTransactionId, 
                    string cardNumber, 
                    string expiryMonth, 
                    string expiryYear, 
                    string buyerName, 
                    string buyerEmail, 
                    string languageId, 
                    string cvv, 
                    string customInfo, 
                    string requestToken, 
                    string ppSellerProtection, 
                    ShippingDetails shippingDetails, 
                    [System.Xml.Serialization.XmlArrayItemAttribute("paymentType", IsNullable=false)] string[] paymentTypes, 
                    PaymentTypeDetail paymentTypeDetail, 
                    string redFraudPrevention, 
                    RedCustomerInfo Red_CustomerInfo, 
                    RedShippingInfo Red_ShippingInfo, 
                    RedBillingInfo Red_BillingInfo, 
                    RedCustomerData Red_CustomerData, 
                    [System.Xml.Serialization.XmlArrayItemAttribute("UserCustomData", IsNullable=false)] string[] Red_CustomInfo, 
                    RedItems Red_Items, 
                    string Consel_MerchantPro, 
                    ConselCustomerInfo Consel_CustomerInfo, 
                    string payPalBillingAgreementDescription) {
            object[] results = this.Invoke("Encrypt", new object[] {
                        shopLogin,
                        uicCode,
                        amount,
                        shopTransactionId,
                        cardNumber,
                        expiryMonth,
                        expiryYear,
                        buyerName,
                        buyerEmail,
                        languageId,
                        cvv,
                        customInfo,
                        requestToken,
                        ppSellerProtection,
                        shippingDetails,
                        paymentTypes,
                        paymentTypeDetail,
                        redFraudPrevention,
                        Red_CustomerInfo,
                        Red_ShippingInfo,
                        Red_BillingInfo,
                        Red_CustomerData,
                        Red_CustomInfo,
                        Red_Items,
                        Consel_MerchantPro,
                        Consel_CustomerInfo,
                        payPalBillingAgreementDescription});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void EncryptAsync(
                    string shopLogin, 
                    string uicCode, 
                    string amount, 
                    string shopTransactionId, 
                    string cardNumber, 
                    string expiryMonth, 
                    string expiryYear, 
                    string buyerName, 
                    string buyerEmail, 
                    string languageId, 
                    string cvv, 
                    string customInfo, 
                    string requestToken, 
                    string ppSellerProtection, 
                    ShippingDetails shippingDetails, 
                    string[] paymentTypes, 
                    PaymentTypeDetail paymentTypeDetail, 
                    string redFraudPrevention, 
                    RedCustomerInfo Red_CustomerInfo, 
                    RedShippingInfo Red_ShippingInfo, 
                    RedBillingInfo Red_BillingInfo, 
                    RedCustomerData Red_CustomerData, 
                    string[] Red_CustomInfo, 
                    RedItems Red_Items, 
                    string Consel_MerchantPro, 
                    ConselCustomerInfo Consel_CustomerInfo, 
                    string payPalBillingAgreementDescription) {
            this.EncryptAsync(shopLogin, uicCode, amount, shopTransactionId, cardNumber, expiryMonth, expiryYear, buyerName, buyerEmail, languageId, cvv, customInfo, requestToken, ppSellerProtection, shippingDetails, paymentTypes, paymentTypeDetail, redFraudPrevention, Red_CustomerInfo, Red_ShippingInfo, Red_BillingInfo, Red_CustomerData, Red_CustomInfo, Red_Items, Consel_MerchantPro, Consel_CustomerInfo, payPalBillingAgreementDescription, null);
        }
        
        /// <remarks/>
        public void EncryptAsync(
                    string shopLogin, 
                    string uicCode, 
                    string amount, 
                    string shopTransactionId, 
                    string cardNumber, 
                    string expiryMonth, 
                    string expiryYear, 
                    string buyerName, 
                    string buyerEmail, 
                    string languageId, 
                    string cvv, 
                    string customInfo, 
                    string requestToken, 
                    string ppSellerProtection, 
                    ShippingDetails shippingDetails, 
                    string[] paymentTypes, 
                    PaymentTypeDetail paymentTypeDetail, 
                    string redFraudPrevention, 
                    RedCustomerInfo Red_CustomerInfo, 
                    RedShippingInfo Red_ShippingInfo, 
                    RedBillingInfo Red_BillingInfo, 
                    RedCustomerData Red_CustomerData, 
                    string[] Red_CustomInfo, 
                    RedItems Red_Items, 
                    string Consel_MerchantPro, 
                    ConselCustomerInfo Consel_CustomerInfo, 
                    string payPalBillingAgreementDescription, 
                    object userState) {
            if ((this.EncryptOperationCompleted == null)) {
                this.EncryptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncryptOperationCompleted);
            }
            this.InvokeAsync("Encrypt", new object[] {
                        shopLogin,
                        uicCode,
                        amount,
                        shopTransactionId,
                        cardNumber,
                        expiryMonth,
                        expiryYear,
                        buyerName,
                        buyerEmail,
                        languageId,
                        cvv,
                        customInfo,
                        requestToken,
                        ppSellerProtection,
                        shippingDetails,
                        paymentTypes,
                        paymentTypeDetail,
                        redFraudPrevention,
                        Red_CustomerInfo,
                        Red_ShippingInfo,
                        Red_BillingInfo,
                        Red_CustomerData,
                        Red_CustomInfo,
                        Red_Items,
                        Consel_MerchantPro,
                        Consel_CustomerInfo,
                        payPalBillingAgreementDescription}, this.EncryptOperationCompleted, userState);
        }
        
        private void OnEncryptOperationCompleted(object arg) {
            if ((this.EncryptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncryptCompleted(this, new EncryptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ecomm.sella.it/Decrypt", RequestNamespace="https://ecomm.sella.it/", ResponseNamespace="https://ecomm.sella.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode Decrypt(string shopLogin, string CryptedString) {
            object[] results = this.Invoke("Decrypt", new object[] {
                        shopLogin,
                        CryptedString});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DecryptAsync(string shopLogin, string CryptedString) {
            this.DecryptAsync(shopLogin, CryptedString, null);
        }
        
        /// <remarks/>
        public void DecryptAsync(string shopLogin, string CryptedString, object userState) {
            if ((this.DecryptOperationCompleted == null)) {
                this.DecryptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDecryptOperationCompleted);
            }
            this.InvokeAsync("Decrypt", new object[] {
                        shopLogin,
                        CryptedString}, this.DecryptOperationCompleted, userState);
        }
        
        private void OnDecryptOperationCompleted(object arg) {
            if ((this.DecryptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DecryptCompleted(this, new DecryptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class ShippingDetails {
        
        private string shipToNameField;
        
        private string shipToStreetField;
        
        private string shipToCityField;
        
        private string shipToStateField;
        
        private string shipToCountryCodeField;
        
        private string shipToZipField;
        
        private string shipToStreet2Field;
        
        /// <remarks/>
        public string shipToName {
            get {
                return this.shipToNameField;
            }
            set {
                this.shipToNameField = value;
            }
        }
        
        /// <remarks/>
        public string shipToStreet {
            get {
                return this.shipToStreetField;
            }
            set {
                this.shipToStreetField = value;
            }
        }
        
        /// <remarks/>
        public string shipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string shipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string shipToCountryCode {
            get {
                return this.shipToCountryCodeField;
            }
            set {
                this.shipToCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string shipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string shipToStreet2 {
            get {
                return this.shipToStreet2Field;
            }
            set {
                this.shipToStreet2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class ConselCustomerInfo {
        
        private string surnameField;
        
        private string nameField;
        
        private string taxationCodeField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateCodeField;
        
        private string dateAddressField;
        
        private string phoneField;
        
        private string mobilePhoneField;
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string TaxationCode {
            get {
                return this.taxationCodeField;
            }
            set {
                this.taxationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DateAddress {
            get {
                return this.dateAddressField;
            }
            set {
                this.dateAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedItem {
        
        private string item_ProductCodeField;
        
        private string item_StockKeepingUnitField;
        
        private string item_DescriptionField;
        
        private string item_QuantityField;
        
        private string item_UnitCostField;
        
        private string item_TotalCostField;
        
        private string item_ShippingNumberField;
        
        private string item_GiftMessageField;
        
        private string item_PartEAN_NumberField;
        
        private string item_ShippingCommentsField;
        
        /// <remarks/>
        public string Item_ProductCode {
            get {
                return this.item_ProductCodeField;
            }
            set {
                this.item_ProductCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Item_StockKeepingUnit {
            get {
                return this.item_StockKeepingUnitField;
            }
            set {
                this.item_StockKeepingUnitField = value;
            }
        }
        
        /// <remarks/>
        public string Item_Description {
            get {
                return this.item_DescriptionField;
            }
            set {
                this.item_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Item_Quantity {
            get {
                return this.item_QuantityField;
            }
            set {
                this.item_QuantityField = value;
            }
        }
        
        /// <remarks/>
        public string Item_UnitCost {
            get {
                return this.item_UnitCostField;
            }
            set {
                this.item_UnitCostField = value;
            }
        }
        
        /// <remarks/>
        public string Item_TotalCost {
            get {
                return this.item_TotalCostField;
            }
            set {
                this.item_TotalCostField = value;
            }
        }
        
        /// <remarks/>
        public string Item_ShippingNumber {
            get {
                return this.item_ShippingNumberField;
            }
            set {
                this.item_ShippingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Item_GiftMessage {
            get {
                return this.item_GiftMessageField;
            }
            set {
                this.item_GiftMessageField = value;
            }
        }
        
        /// <remarks/>
        public string Item_PartEAN_Number {
            get {
                return this.item_PartEAN_NumberField;
            }
            set {
                this.item_PartEAN_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string Item_ShippingComments {
            get {
                return this.item_ShippingCommentsField;
            }
            set {
                this.item_ShippingCommentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedItems {
        
        private string numberOfItemsField;
        
        private RedItem[] red_ItemField;
        
        /// <remarks/>
        public string NumberOfItems {
            get {
                return this.numberOfItemsField;
            }
            set {
                this.numberOfItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Red_Item")]
        public RedItem[] Red_Item {
            get {
                return this.red_ItemField;
            }
            set {
                this.red_ItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedCustomerData {
        
        private string merchantWebSiteField;
        
        private string customer_IPAddressField;
        
        private string pC_FingerPrintField;
        
        private string previousCustomerField;
        
        private string red_Merchant_IDField;
        
        private string red_ServiceTypeField;
        
        /// <remarks/>
        public string MerchantWebSite {
            get {
                return this.merchantWebSiteField;
            }
            set {
                this.merchantWebSiteField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_IPAddress {
            get {
                return this.customer_IPAddressField;
            }
            set {
                this.customer_IPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string PC_FingerPrint {
            get {
                return this.pC_FingerPrintField;
            }
            set {
                this.pC_FingerPrintField = value;
            }
        }
        
        /// <remarks/>
        public string PreviousCustomer {
            get {
                return this.previousCustomerField;
            }
            set {
                this.previousCustomerField = value;
            }
        }
        
        /// <remarks/>
        public string Red_Merchant_ID {
            get {
                return this.red_Merchant_IDField;
            }
            set {
                this.red_Merchant_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Red_ServiceType {
            get {
                return this.red_ServiceTypeField;
            }
            set {
                this.red_ServiceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedBillingInfo {
        
        private string billing_IdField;
        
        private string billing_NameField;
        
        private string billing_SurnameField;
        
        private string billing_DateOfBirthField;
        
        private string billing_EmailField;
        
        private string billing_AddressField;
        
        private string billing_Address2Field;
        
        private string billing_CityField;
        
        private string billing_StateCodeField;
        
        private string billing_CountryField;
        
        private string billing_PostalCodeField;
        
        private string billing_HomePhoneField;
        
        private string billing_WorkPhoneField;
        
        private string billing_MobilePhoneField;
        
        /// <remarks/>
        public string Billing_Id {
            get {
                return this.billing_IdField;
            }
            set {
                this.billing_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_Name {
            get {
                return this.billing_NameField;
            }
            set {
                this.billing_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_Surname {
            get {
                return this.billing_SurnameField;
            }
            set {
                this.billing_SurnameField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_DateOfBirth {
            get {
                return this.billing_DateOfBirthField;
            }
            set {
                this.billing_DateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_Email {
            get {
                return this.billing_EmailField;
            }
            set {
                this.billing_EmailField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_Address {
            get {
                return this.billing_AddressField;
            }
            set {
                this.billing_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_Address2 {
            get {
                return this.billing_Address2Field;
            }
            set {
                this.billing_Address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Billing_City {
            get {
                return this.billing_CityField;
            }
            set {
                this.billing_CityField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_StateCode {
            get {
                return this.billing_StateCodeField;
            }
            set {
                this.billing_StateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_Country {
            get {
                return this.billing_CountryField;
            }
            set {
                this.billing_CountryField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_PostalCode {
            get {
                return this.billing_PostalCodeField;
            }
            set {
                this.billing_PostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_HomePhone {
            get {
                return this.billing_HomePhoneField;
            }
            set {
                this.billing_HomePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_WorkPhone {
            get {
                return this.billing_WorkPhoneField;
            }
            set {
                this.billing_WorkPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_MobilePhone {
            get {
                return this.billing_MobilePhoneField;
            }
            set {
                this.billing_MobilePhoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedShippingInfo {
        
        private string shipping_NameField;
        
        private string shipping_SurnameField;
        
        private string shipping_EmailField;
        
        private string shipping_AddressField;
        
        private string shipping_Address2Field;
        
        private string shipping_CityField;
        
        private string shipping_StateCodeField;
        
        private string shipping_CountryField;
        
        private string shipping_PostalCodeField;
        
        private string shipping_HomePhoneField;
        
        private string shipping_MobilePhoneField;
        
        private string shipping_FaxPhoneField;
        
        private string shipping_TimeToDepartureField;
        
        /// <remarks/>
        public string Shipping_Name {
            get {
                return this.shipping_NameField;
            }
            set {
                this.shipping_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Surname {
            get {
                return this.shipping_SurnameField;
            }
            set {
                this.shipping_SurnameField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Email {
            get {
                return this.shipping_EmailField;
            }
            set {
                this.shipping_EmailField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Address {
            get {
                return this.shipping_AddressField;
            }
            set {
                this.shipping_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Address2 {
            get {
                return this.shipping_Address2Field;
            }
            set {
                this.shipping_Address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_City {
            get {
                return this.shipping_CityField;
            }
            set {
                this.shipping_CityField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_StateCode {
            get {
                return this.shipping_StateCodeField;
            }
            set {
                this.shipping_StateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Country {
            get {
                return this.shipping_CountryField;
            }
            set {
                this.shipping_CountryField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_PostalCode {
            get {
                return this.shipping_PostalCodeField;
            }
            set {
                this.shipping_PostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_HomePhone {
            get {
                return this.shipping_HomePhoneField;
            }
            set {
                this.shipping_HomePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_MobilePhone {
            get {
                return this.shipping_MobilePhoneField;
            }
            set {
                this.shipping_MobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_FaxPhone {
            get {
                return this.shipping_FaxPhoneField;
            }
            set {
                this.shipping_FaxPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_TimeToDeparture {
            get {
                return this.shipping_TimeToDepartureField;
            }
            set {
                this.shipping_TimeToDepartureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class RedCustomerInfo {
        
        private string customer_TitleField;
        
        private string customer_NameField;
        
        private string customer_SurnameField;
        
        private string customer_EmailField;
        
        private string customer_AddressField;
        
        private string customer_Address2Field;
        
        private string customer_CityField;
        
        private string customer_StateCodeField;
        
        private string customer_CountryField;
        
        private string customer_PostalCodeField;
        
        private string customer_PhoneField;
        
        /// <remarks/>
        public string Customer_Title {
            get {
                return this.customer_TitleField;
            }
            set {
                this.customer_TitleField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Name {
            get {
                return this.customer_NameField;
            }
            set {
                this.customer_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Surname {
            get {
                return this.customer_SurnameField;
            }
            set {
                this.customer_SurnameField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Email {
            get {
                return this.customer_EmailField;
            }
            set {
                this.customer_EmailField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Address {
            get {
                return this.customer_AddressField;
            }
            set {
                this.customer_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Address2 {
            get {
                return this.customer_Address2Field;
            }
            set {
                this.customer_Address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Customer_City {
            get {
                return this.customer_CityField;
            }
            set {
                this.customer_CityField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_StateCode {
            get {
                return this.customer_StateCodeField;
            }
            set {
                this.customer_StateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Country {
            get {
                return this.customer_CountryField;
            }
            set {
                this.customer_CountryField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_PostalCode {
            get {
                return this.customer_PostalCodeField;
            }
            set {
                this.customer_PostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_Phone {
            get {
                return this.customer_PhoneField;
            }
            set {
                this.customer_PhoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ecomm.sella.it/")]
    public partial class PaymentTypeDetail {
        
        private string myBankBankCodeField;
        
        private string idealBankCodeField;
        
        /// <remarks/>
        public string MyBankBankCode {
            get {
                return this.myBankBankCodeField;
            }
            set {
                this.myBankBankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IdealBankCode {
            get {
                return this.idealBankCodeField;
            }
            set {
                this.idealBankCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EncryptCompletedEventHandler(object sender, EncryptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncryptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncryptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DecryptCompletedEventHandler(object sender, DecryptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DecryptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DecryptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591