<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="iFrameProjectExample.WebForm1" %>
<!DOCTYPE html>
<html>
<head>
<title>iFrame Example</title>
 <!-- Load the GestPay javascript file -->
<!-- Production -->
<!--script type="text/javascript" src="https://ecomm.sella.it/Pagam/JavaScript/js_GestPay.js"></script -->
<!-- TEST --> 
<script type="text/javascript" src="https://testecomm.sella.it/Pagam/JavaScript/js_GestPay.js"></script>
<script type="text/javascript">
    //declaring local object to handle asynchronous responses from the payment page 
    var LocalObj = {}
    //setting up a function to handle asynchronous security check result after creating the iFrame and loading the payment page
    LocalObj.PaymentPageLoad = function (Result) {
        //check for errors, if the Result.ErroCode is 10 the iFrame is created correctly and the security check are passed 
        if (Result.ErrorCode == 10) {
            //iFrame created and and the security check passed 
            //Handle 3D authentication 2nd call
            var PARes = '<%Response.Write(PARes);%>';
            if (PARes.length > 0) {
                //The card holder land for the 2nd call after 3d authentication so we can proceed to process the transaction without showing the form 
                document.getElementById('text').innerHTML = 'Payment in progress...';
                GestPay.SendPayment({ PARes: PARes, TransKey: '<%Response.Write(TransKey);%>' }, LocalObj.PaymentCallBack);
            } else {
                document.getElementById('InnerFreezePane').className = 'Off';
                document.getElementById('FreezePane').className = 'Off';
                document.getElementById('CCForm').className = 'On';
                document.getElementById('submit').disabled = false;
            }
            //now we can show the form with the credit card fields
        } else {
            //An error has occurred, check the Result.ErrorCode and Result.ErrorDescription 
            //place error handle code HERE
            document.getElementById('ErrorBox').innerHTML = 'Error:' + Result.ErrorCode + ' ' + Result.ErrorDescription;
            document.getElementById('ErrorBox').className = 'On'
            document.getElementById('InnerFreezePane').className = 'Off'
            document.getElementById('FreezePane').className = 'Off'
        }
    }
    //setting up a function to handle payment result
    LocalObj.PaymentCallBack = function (Result) {
        if (Result.ErrorCode == 0) {
            //Transaction correctly processed
            //Decrypt the string to read the Transaction Result
            document.location.replace('response.aspx?a=<%Response.Write(Shop_Login);%>&b=' + Result.EncryptedString);
        } else {
            //An error has occurred
            //check for 3D authentication required
            if (Result.ErrorCode == 8006) {
                //The credit card is enrolled we must send the card holder to the authentication page on the issuer website
                //Get the TransKey, IMPORTANT! this value must be stored for further use
                var TransKey = Result.TransKey
                //put the TransKey in a cookie for later use, the cookies will expire in 20 minutes
                document.cookie = 'TransKey=' + TransKey + '; path=/';
                //put the EcryptedString generated by the WSCryptDecrypt webservice in a cookies for later use the cookies will expire in 20 minutes
                document.cookie = 'encString=<%Response.Write(EncryptedString);%>; path=/';
                //Get the VBVRisp encrypted string required to access the issuer authentication page
                var VBVRisp = Result.VBVRisp
                //redirect the user to the issuer authentication pages
                var a = 'Response.Write(Shop_Login);%>';
                var b = VBVRisp;
                var c = document.location.href; //this is the landing page where the user will be redirected after the issuer authentication must be ABSOLUTE
                var AuthUrl = 'https://testecomm.sella.it/pagam/pagam3d.aspx'; //TESTCODES
                //var AuthUrl = "https://ecomm.sella.it/pagam/pagam3d.aspx"; //PRODUCTION
                document.location.replace(AuthUrl + '?a=' + a + '&b=' + b + '&c=' + c);
            } else {
                //Hide overlapping layer
                document.getElementById('InnerFreezePane').className = 'Off';
                document.getElementById('FreezePane').className = 'Off';
                document.getElementById('submit').disabled = false;
                //Check the ErrorCode and ErrorDescription
                if (Result.ErrorCode == 1119 || Result.ErrorCode == 1120) {
                    document.getElementById('ErrorBox').innerHTML = 'Error:' + Result.ErrorCode + ' - ' + Result.ErrorDescription;
                    document.getElementById('ErrorBox').className = 'On';
                    document.getElementById('CC').focus();
                }
                if (Result.ErrorCode == 1124 || Result.ErrorCode == 1126) {
                    document.getElementById('ErrorBox').innerHTML = 'Error:' + Result.ErrorCode + ' - ' + Result.ErrorDescription;
                    document.getElementById('ErrorBox').className = 'On';
                    document.getElementById('EXPMM').focus();
                }
                if (Result.ErrorCode == 1125) {
                    document.getElementById('ErrorBox').innerHTML = 'Error:' + Result.ErrorCode + ' - ' + Result.ErrorDescription;
                    document.getElementById('ErrorBox').className = 'On';
                    document.getElementById('EXPYY').focus();
                }
                if (Result.ErrorCode == 1149) {
                    document.getElementById('ErrorBox').innerHTML = 'Error:' + Result.ErrorCode + ' - ' + Result.ErrorDescription;
                    document.getElementById('ErrorBox').className = 'On';
                    document.getElementById('CVV2').focus();
                }
                if (Result.ErrorCode != 1149 || Result.ErrorCode != 1119 || Result.ErrorCode != 1120 || Result.ErrorCode != 1124 || Result.ErrorCode != 1126 || Result.ErrorCode != 1125) {
                    document.getElementById('ErrorBox').innerHTML = 'Error:' + Result.ErrorCode + ' - ' + Result.ErrorDescription;
                    document.getElementById('ErrorBox').className = 'On'
                }
                if (Result.ErrorCode == 4707) {
                    //the second call after 3D authentication has been sent twice or more
                    //response string was sent to the URL Server to Server if any address is set on the Merchant Back Office
                    //to retrieve transaction result make an ajax call to a function that will access the DB 
                    document.getElementById('ErrorBox').innerHTML = 'Error:' + Result.ErrorCode + ' - ' + Result.ErrorDescription;
                    document.getElementById('ErrorBox').className = 'On'
                }
            }
        }
    }

    //Send data to GestPay and process transaction
    function CheckCC() {
        document.getElementById('submit').disabled = true; //disable submit button
        //raise the Overlap layer
        document.getElementById('FreezePane').className = 'FreezePaneOn';
        //raise the loading message
        document.getElementById('text').innerHTML = 'Payment in Progress...';
        document.getElementById('InnerFreezePane').className = 'On';
        GestPay.SendPayment({
            CC: document.getElementById('CC').value,
            EXPMM: document.getElementById('EXPMM').value,
            EXPYY: document.getElementById('EXPYY').value,
            CVV2: document.getElementById('CVV2').value,
            Name: document.getElementById('Name').value,
            Email: document.getElementById('Email').value
        }, LocalObj.PaymentCallBack);
        return false;

    }


</script>
<link type="text/css" rel="stylesheet" href="Styles/reset.css">
<link type="text/css" rel="stylesheet" href="Styles/iFrame.css">

<!--[if IE]>
      <style type="text/css">
   #CCFieldset{
	background-color:#FFF;
	width:510px;
    }
    #CCcontainer{
    	width:500px;
    	
    }
    #CCcontainer div{
    	width: 350px;
    	margin:0 auto;
    }
    
   </style>
<![endif]-->

<!--[if lte IE 8]>
 <style type="text/css">
input{
	background-color:rgb(235,235,235);
	padding: 0.7em;

}
</style>
<![endif]-->


</head>
<body>
<!-- Overlap Layer -->
<div id="FreezePane" class="Off"></div>
<div id="InnerFreezePane" class="Off">
	<div id="text"></div>
</div>
<!-- Overlap Layer END -->
<!-- ErrorBox -->
<div id="ErrorBox" class="<%Response.Write(ErrorClass);%>">Error:<%Response.Write(ErrorCode);%> - <%Response.Write(ErrorDescription);%></div>
<!-- Create the iFrame-->
<script type="text/javascript">
    //check if the browser support HTML5 postmessage
    if (BrowserEnabled) {
        //Browser enabled
        //Check for errors during the parameters encryption 
        var ErrorCode = '<%Response.Write(ErrorCode);%>';
        if (ErrorCode == 0) {
            //Creating the iFrame
            GestPay.CreatePaymentPage('<%Response.Write(Shop_Login);%>', '<%Response.Write(EncryptedString);%>', LocalObj.PaymentPageLoad);
            //raise the Overlap layer
            document.getElementById('FreezePane').className = 'FreezePaneOn';
            //raise the loading message
            document.getElementById('text').innerHTML = 'Loading...';
            document.getElementById('InnerFreezePane').className = 'On';
        } else {
            //errors found during the parameter encryption
            //place error handle code here
            document.getElementById('ErrorBox').className = 'On';
        }
    } else {
        //Browser not supported
        //Place error handle code here
        document.getElementById('ErrorBox').innerHTML = 'Error: Browser not supported';
        document.getElementById('ErrorBox').className = 'On';
    }
</script>
<!-- main Box -->
<div id="Main">
	<!-- Credit card form, hidden before browser check and untill the iFrame is properly loaded -->
	<form name="CCForm" method="post" id="CCForm" OnSubmit="return CheckCC();" class="Off">
		<div id="Fields">
		<fieldset id="CCFieldset">
		<legend>Credit card data</legend>
			<div id="CCcontainer">
			<div id="CCField"><label for="CC">Card Number</label><div class="fieldcontainerL"><input type="text" name="CC" id="CC" autocomplete="off" maxlength="19" placeholder="4444444444444444"/></div></div>
			<div id="ExpDate"><label>Exipiry Date (MM/YY)</label><div class="fieldcontainerS"><input type="text" name="EXPMM" id="EXPMM" autocomplete="off" maxlength="2" placeholder="01" /></div> / <div class="fieldcontainerS"><input type="text" name="EXPYY" id="EXPYY" autocomplete="off" maxlength="2"  placeholder="18"/></div>
			</div>
			<hr/>
			<div id="CCVField"><label>Security code (Cvv2/4DBC)</label><div class="fieldcontainerS"><input type="password" name="CVV2" id="CVV2" maxlength="4" /></div></div>
			<hr />
			<div id="NameField"><label for="Name">Buyer Name</label><div class="fieldcontainerL"><input type="text" name="Name" id="Name" value=""></div></div>
			<hr />
			<div id="EmailField"><label for="Email">Buyer Email</label><div class="fieldcontainerL"><input type="email" name="Email" id="Email" value=""></div></div>
			</div>
		</fieldset>
		<fieldset id="SubmitFieldset">	
			<input type="submit" value="Proceed" id="submit" />
		</fieldset>
		</div>
	</form>
</div>
</body>
</html>
